dist: xenial
language: cpp

matrix:
  include:

  #
  # varcoin release-all (gcc)
  #
  - os: linux
    compiler: gcc
    addons:
      apt:
        packages:
          - build-essential
          - cmake
          - g++
          - gcc
          - clang
          - libdb++-dev
          - libdb-dev
          - libgtest-dev
          - libminiupnpc-dev
          - libssl-dev
          - libssl1.0.0
      sources:
        - ubuntu-toolchain-r-test
    before_install:
      - sudo apt-get -q update
    install:
      - sudo apt-get -y install libboost-{chrono,program-options,date-time,thread,system,filesystem,regex,serialization}1.58{-dev,.0}
    script:
      - chmod 777 * -R ; mkdir build; cd build
      - cmake .. && make -j2
      - mkdir gh-pages ; cd gh-pages
      - mkdir bin ; cp ../src/varcoind bin ; cp ../src/miner bin ; cp ../src/connectivity_tool bin ; cp ../src/walletd bin ; cp ../src/simplewallet bin
      - mkdir tests ; cp ../tests/*_tests tests
      - git init && git config user.name "xqymain" && git config user.email "201330010330@hnu.edu.cn" && git lfs install && git lfs trace * && git checkout -b gh-pages && git add . && git commit -m "Update Releases" && git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages 

env:
  global:
    - GH_REF: github.com/xqymain/varcoin.git
