sudo: required
dist: xenial
os: linux
language: c++
#env:
#  global:
#    - MAKEJOBS=-j3
  matrix:
# ARM
    - HOST=arm-linux-gnueabihf PACKAGES="g++-arm-linux-gnueabihf"
# Win32
    - HOST=i686-w64-mingw32 DPKG_ADD_ARCH="i386" PACKAGES="nsis g++-mingw-w64-i686 wine1.6" 
# system libs
    - HOST=x86_64-unknown-linux-gnu PACKAGES="libssl-dev libevent-dev bsdmainutils libdb5.1++-dev libminiupnpc-dev"
# 32-bit
    - HOST=i686-pc-linux-gnu PACKAGES="g++-multilib"
# Win64
    - HOST=x86_64-w64-mingw32 DPKG_ADD_ARCH="i386" PACKAGES="nsis g++-mingw-w64-x86-64 wine1.6"
# Cross-Mac
    - HOST=x86_64-apple-darwin11 PACKAGES="cmake imagemagick libcap-dev librsvg2-bin libz-dev libbz2-dev libtiff-tools"

before_install:
#    - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
    sudo apt-get -q update
#install:
       
before_script:
      - cd ../
      - wget -c 'http://sourceforge.net/projects/boost/files/boost/1.67.0/boost_1_67_0.tar.bz2/download' && tar xf download && rm download && mv boost_1_67_0 boost && cd boost && ./bootstrap.sh && ./b2 link=static -j 2 --build-dir=build64 --stagedir=stage && cd ../
      - git clone https://github.com/openssl/openssl.git && cd openssl && ./Configure linux-x86_64 no-shared && make -j2 && cd ../
      - git clone https://github.com/LMDB/lmdb.git
      - ls ; cd varcoin
      - mkdir build; cd build
      - cmake .. && make -j2
#after_script:
#    - echo $TRAVIS_COMMIT_RANGE
#    - echo $TRAVIS_COMMIT_LOG
