# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/varcoin_lib

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/varcoin_lib

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/varcoin_lib/CMakeFiles /root/varcoin_lib/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/varcoin_lib/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named version

# Build rule for target.
version: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 version
.PHONY : version

# fast build rule for target.
version/fast:
	$(MAKE) -f CMakeFiles/version.dir/build.make CMakeFiles/version.dir/build
.PHONY : version/fast

#=============================================================================
# Target rules for targets named upnpc-static

# Build rule for target.
upnpc-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 upnpc-static
.PHONY : upnpc-static

# fast build rule for target.
upnpc-static/fast:
	$(MAKE) -f external/miniupnpc/CMakeFiles/upnpc-static.dir/build.make external/miniupnpc/CMakeFiles/upnpc-static.dir/build
.PHONY : upnpc-static/fast

#=============================================================================
# Target rules for targets named daemon

# Build rule for target.
daemon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 daemon
.PHONY : daemon

# fast build rule for target.
daemon/fast:
	$(MAKE) -f src/CMakeFiles/daemon.dir/build.make src/CMakeFiles/daemon.dir/build
.PHONY : daemon/fast

#=============================================================================
# Target rules for targets named crypto

# Build rule for target.
crypto: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 crypto
.PHONY : crypto

# fast build rule for target.
crypto/fast:
	$(MAKE) -f src/CMakeFiles/crypto.dir/build.make src/CMakeFiles/crypto.dir/build
.PHONY : crypto/fast

#=============================================================================
# Target rules for targets named connectivity_tool

# Build rule for target.
connectivity_tool: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 connectivity_tool
.PHONY : connectivity_tool

# fast build rule for target.
connectivity_tool/fast:
	$(MAKE) -f src/CMakeFiles/connectivity_tool.dir/build.make src/CMakeFiles/connectivity_tool.dir/build
.PHONY : connectivity_tool/fast

#=============================================================================
# Target rules for targets named rpc

# Build rule for target.
rpc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rpc
.PHONY : rpc

# fast build rule for target.
rpc/fast:
	$(MAKE) -f src/CMakeFiles/rpc.dir/build.make src/CMakeFiles/rpc.dir/build
.PHONY : rpc/fast

#=============================================================================
# Target rules for targets named node_rpc_proxy

# Build rule for target.
node_rpc_proxy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 node_rpc_proxy
.PHONY : node_rpc_proxy

# fast build rule for target.
node_rpc_proxy/fast:
	$(MAKE) -f src/CMakeFiles/node_rpc_proxy.dir/build.make src/CMakeFiles/node_rpc_proxy.dir/build
.PHONY : node_rpc_proxy/fast

#=============================================================================
# Target rules for targets named common

# Build rule for target.
common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 common
.PHONY : common

# fast build rule for target.
common/fast:
	$(MAKE) -f src/CMakeFiles/common.dir/build.make src/CMakeFiles/common.dir/build
.PHONY : common/fast

#=============================================================================
# Target rules for targets named wallet

# Build rule for target.
wallet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wallet
.PHONY : wallet

# fast build rule for target.
wallet/fast:
	$(MAKE) -f src/CMakeFiles/wallet.dir/build.make src/CMakeFiles/wallet.dir/build
.PHONY : wallet/fast

#=============================================================================
# Target rules for targets named VarNote_core

# Build rule for target.
VarNote_core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 VarNote_core
.PHONY : VarNote_core

# fast build rule for target.
VarNote_core/fast:
	$(MAKE) -f src/CMakeFiles/VarNote_core.dir/build.make src/CMakeFiles/VarNote_core.dir/build
.PHONY : VarNote_core/fast

#=============================================================================
# Target rules for targets named simpleminer

# Build rule for target.
simpleminer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simpleminer
.PHONY : simpleminer

# fast build rule for target.
simpleminer/fast:
	$(MAKE) -f src/CMakeFiles/simpleminer.dir/build.make src/CMakeFiles/simpleminer.dir/build
.PHONY : simpleminer/fast

#=============================================================================
# Target rules for targets named simplewallet

# Build rule for target.
simplewallet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simplewallet
.PHONY : simplewallet

# fast build rule for target.
simplewallet/fast:
	$(MAKE) -f src/CMakeFiles/simplewallet.dir/build.make src/CMakeFiles/simplewallet.dir/build
.PHONY : simplewallet/fast

#=============================================================================
# Target rules for targets named difficulty-tests

# Build rule for target.
difficulty-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 difficulty-tests
.PHONY : difficulty-tests

# fast build rule for target.
difficulty-tests/fast:
	$(MAKE) -f tests/CMakeFiles/difficulty-tests.dir/build.make tests/CMakeFiles/difficulty-tests.dir/build
.PHONY : difficulty-tests/fast

#=============================================================================
# Target rules for targets named crypto-tests

# Build rule for target.
crypto-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 crypto-tests
.PHONY : crypto-tests

# fast build rule for target.
crypto-tests/fast:
	$(MAKE) -f tests/CMakeFiles/crypto-tests.dir/build.make tests/CMakeFiles/crypto-tests.dir/build
.PHONY : crypto-tests/fast

#=============================================================================
# Target rules for targets named performance_tests

# Build rule for target.
performance_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 performance_tests
.PHONY : performance_tests

# fast build rule for target.
performance_tests/fast:
	$(MAKE) -f tests/CMakeFiles/performance_tests.dir/build.make tests/CMakeFiles/performance_tests.dir/build
.PHONY : performance_tests/fast

#=============================================================================
# Target rules for targets named coretests_lib

# Build rule for target.
coretests_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 coretests_lib
.PHONY : coretests_lib

# fast build rule for target.
coretests_lib/fast:
	$(MAKE) -f tests/CMakeFiles/coretests_lib.dir/build.make tests/CMakeFiles/coretests_lib.dir/build
.PHONY : coretests_lib/fast

#=============================================================================
# Target rules for targets named hash-target-tests

# Build rule for target.
hash-target-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hash-target-tests
.PHONY : hash-target-tests

# fast build rule for target.
hash-target-tests/fast:
	$(MAKE) -f tests/CMakeFiles/hash-target-tests.dir/build.make tests/CMakeFiles/hash-target-tests.dir/build
.PHONY : hash-target-tests/fast

#=============================================================================
# Target rules for targets named hash-tests

# Build rule for target.
hash-tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hash-tests
.PHONY : hash-tests

# fast build rule for target.
hash-tests/fast:
	$(MAKE) -f tests/CMakeFiles/hash-tests.dir/build.make tests/CMakeFiles/hash-tests.dir/build
.PHONY : hash-tests/fast

#=============================================================================
# Target rules for targets named functional_tests

# Build rule for target.
functional_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 functional_tests
.PHONY : functional_tests

# fast build rule for target.
functional_tests/fast:
	$(MAKE) -f tests/CMakeFiles/functional_tests.dir/build.make tests/CMakeFiles/functional_tests.dir/build
.PHONY : functional_tests/fast

#=============================================================================
# Target rules for targets named node_rpc_proxy_test

# Build rule for target.
node_rpc_proxy_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 node_rpc_proxy_test
.PHONY : node_rpc_proxy_test

# fast build rule for target.
node_rpc_proxy_test/fast:
	$(MAKE) -f tests/CMakeFiles/node_rpc_proxy_test.dir/build.make tests/CMakeFiles/node_rpc_proxy_test.dir/build
.PHONY : node_rpc_proxy_test/fast

#=============================================================================
# Target rules for targets named net_load_tests_srv

# Build rule for target.
net_load_tests_srv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 net_load_tests_srv
.PHONY : net_load_tests_srv

# fast build rule for target.
net_load_tests_srv/fast:
	$(MAKE) -f tests/CMakeFiles/net_load_tests_srv.dir/build.make tests/CMakeFiles/net_load_tests_srv.dir/build
.PHONY : net_load_tests_srv/fast

#=============================================================================
# Target rules for targets named net_load_tests_clt

# Build rule for target.
net_load_tests_clt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 net_load_tests_clt
.PHONY : net_load_tests_clt

# fast build rule for target.
net_load_tests_clt/fast:
	$(MAKE) -f tests/CMakeFiles/net_load_tests_clt.dir/build.make tests/CMakeFiles/net_load_tests_clt.dir/build
.PHONY : net_load_tests_clt/fast

#=============================================================================
# Target rules for targets named tests

# Build rule for target.
tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests
.PHONY : tests

# fast build rule for target.
tests/fast:
	$(MAKE) -f tests/CMakeFiles/tests.dir/build.make tests/CMakeFiles/tests.dir/build
.PHONY : tests/fast

#=============================================================================
# Target rules for targets named coretests

# Build rule for target.
coretests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 coretests
.PHONY : coretests

# fast build rule for target.
coretests/fast:
	$(MAKE) -f tests/CMakeFiles/coretests.dir/build.make tests/CMakeFiles/coretests.dir/build
.PHONY : coretests/fast

#=============================================================================
# Target rules for targets named core_proxy

# Build rule for target.
core_proxy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 core_proxy
.PHONY : core_proxy

# fast build rule for target.
core_proxy/fast:
	$(MAKE) -f tests/CMakeFiles/core_proxy.dir/build.make tests/CMakeFiles/core_proxy.dir/build
.PHONY : core_proxy/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f tests/gtest/CMakeFiles/gtest.dir/build.make tests/gtest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f tests/gtest/CMakeFiles/gtest_main.dir/build.make tests/gtest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... rebuild_cache"
	@echo "... version"
	@echo "... edit_cache"
	@echo "... install/local"
	@echo "... test"
	@echo "... upnpc-static"
	@echo "... daemon"
	@echo "... crypto"
	@echo "... connectivity_tool"
	@echo "... rpc"
	@echo "... node_rpc_proxy"
	@echo "... common"
	@echo "... wallet"
	@echo "... VarNote_core"
	@echo "... simpleminer"
	@echo "... simplewallet"
	@echo "... difficulty-tests"
	@echo "... crypto-tests"
	@echo "... performance_tests"
	@echo "... coretests_lib"
	@echo "... hash-target-tests"
	@echo "... hash-tests"
	@echo "... functional_tests"
	@echo "... node_rpc_proxy_test"
	@echo "... net_load_tests_srv"
	@echo "... net_load_tests_clt"
	@echo "... tests"
	@echo "... coretests"
	@echo "... core_proxy"
	@echo "... gtest"
	@echo "... gtest_main"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

